version: '3.8'

services:
  test_api:
    container_name: test_api
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      sh -c "
        pytest -vv --disable-warnings
      "
    environment:
      CONFIG_FILE: ".test.env"
    networks:
      - test_network
    depends_on:
      test-db:
        condition: service_healthy
      cache_data_test:
        condition: service_healthy
  cache_data_test:
    image: redis:latest
    container_name: test-redis
    volumes:
      - redis_data_test:/var/lib/redis_test/data/
    expose:
      - 6379
    restart: on-failure
    env_file:
      - ".test.env"
    networks:
      - test_network
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  test-db:
    image: postgres:15.1-alpine
    container_name: test-db
    volumes:
      - postgres_data_test:/var/lib/postgresql_tests/data/
    expose:
      - 5432
    env_file:
      - ".test.env"
    restart: on-failure
    networks:
      - test_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  test_network:
    external: false

volumes:
  postgres_data_test:
  redis_data_test:
